services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./shared:/shared
    environment:
      POSTGRES_PASSWORD: postgres